### PR TITLE
update NSNumber prop attributes from assign -> strong

### LINKED ISSUE #1450: EXC_BAD_ACCESS: hash > retain > style > Attempted to dereference garbage pointer 0xe.
After our latest release we started getting hammered by EXC_BAD_ACCESS fetal errors and NSInvalidArgument exceptions. We have been unable to reproduce the issue locally, and are only seeing crashes with iOS. We are using Sentry for our production error reporting. 

Environment: 
"@mapbox/react-native-mapbox-gl": "^6.1.2",
 "react-native": "0.57.8",

Stack trace: 
screen shot 2018-12-21 at 10 24 03 am

### PR DESCRIPTION
**Pull request by L-Yeiser**
Proposed fix [for](https://github.com/mapbox/react-native-mapbox-gl/issues/1450)

### CODE REVIEW

**Comment by kristfal** [comment]
@l-yeiser can you confirm if this fix does indeed solve the issue in production? (Ex: push your fork to production and check for crashes)

**Comment by L-Yeiser** [comment]
The fork was released to production two weeks ago and we have not seen that crash on that release.

**Comment by orta** [comment]
Can confirm, an NSObject subclass like these should never be `assign`

**Comment by nitaliano** [comment]
I totally agree with this thanks for the PR! 😄

**Pull request merged**
