### PR TITLE
RCTMapboxGL.xcodeproj should be added to the Libraries folder

### PR DESCRIPTION
**Pull request by statiklabs**

### CODE REVIEW

**Comment by 1ec5** [comment]
I suppose the screenshot needs to be updated too.

**Comment by henrikra** [comment]
If you look the screenshot it is fine by my standards :D Merge?

**Comment by 1ec5** [comment]
I was referring to the inclusion of https://dl.dropboxusercontent.com/s/6trwtezp3009eot/2016-03-14%20at%2012.52%20PM.png, which has gone away. Anyhow, this change seems OK.

**Comment by henrikra** [comment]
@1ec5 Can't see your image:
image

**Comment by 1ec5** [comment]
Yeah, that’s what I meant. I can’t see it either. 😄

**Comment by henrikra** [comment]
Ah lol 😅

**Pull request merged**
