### PR TITLE
Update to mapbox gl native 2.1.2

### PR DESCRIPTION
**Pull request by bsudekum**
This updates to mapbox-gl-native 2.1.2 and fixes many stability issues.

/cc @1ec5

### CODE REVIEW

**Comment by bsudekum** [comment]
I'm getting the following when building for the device even with bitcode set to false:

```
ld: '/Users/bobby/Library/Developer/Xcode/DerivedData/test50-azpglrbhtoiaqaabqftftxfvnxzu/Build/Products/Debug-iphoneos/libRCTMapboxGL.a(RCTMapboxGL.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by friedbunny** [comment]
Couple things to check:
- Deep clean your Xcode build: control+option+shift+k
- Is bitcode actually disabled everywhere? Check the Build Settings for the project and the main app target, then do the same for `RCTMapboxWhatever.xcodeproj`.

bitcode_ugh

**Comment by bsudekum** [comment]
> Is bitcode actually disabled everywhere? Check the Build Settings for the project and the main app target, then do the same for RCTMapboxWhatever.xcodeproj.

Yeah I found a missing one. Disabled bitcode everywhere and it's now building fine.

**Comment by friedbunny** [comment]
Turning off bitcode at the project-level is going to be a requirement until we can get around https://github.com/mapbox/mapbox-gl-native/issues/2332 and land bitcode support for iOS.

**Pull request merged**
