### PR TITLE
7.0.0

### PR DESCRIPTION
**Pull request by nitaliano**
This will be the branch for the next major release. There is still some experimenting to do, but I will work on getting this thing stable and merged into master.

This is a good example that shows off the new expressions API https://github.com/mapbox/react-native-mapbox-gl/blob/492e1522f7d18f05feaf9ff9ec6d9cccbffb3c92/example/src/examples/FlyTo.js I wouldn't attempt to use this branch in any current projects yet, wait until we get this merged into master

### CODE REVIEW

**Comment by StasDoskalenko** [comment]
@nitaliano hey! Thank you so much! This looks awesome :)
I'll take a try

**Comment by nitaliano** [comment]
expect a large sweeping change of native code to hit this branch

**Comment by wdimmit** [comment]
I've just added two issues related to this PR:

https://github.com/mapbox/react-native-mapbox-gl/issues/1390
https://github.com/mapbox/react-native-mapbox-gl/issues/1389

**Comment by StasDoskalenko** [comment]
Guys any updates here?

**Comment by EricPKerr** [comment]
@nitaliano thanks for the help on this - any idea what's remaining to release this?

**Comment by makirby** [comment]
Is this project still going to be maintained? @mapbox

**Comment by StasDoskalenko** [comment]
@nitaliano @mapbox so as I understand we even don't need to remove Point Annotations, correct?
https://www.mapbox.com/android-docs/plugins/overview/markerview/

**Comment by zolero** [comment]
Why can't we develop with you using this branch? Release it as beta already. And why does it have to take so long?

**Comment by zolero** [comment]
ETA?

**Comment by GISerWYJ** [comment]
when will the new version be released? @nitaliano

**Comment by systemlevel** [comment]
> when will the new version be released? @nitaliano

@zugaldia @nitaliano 

I know you guys are probably tired of being asked this question but for technical planning on some major projects it would be great to have a general idea of when 7.0 might land.  The previous docs reference the timeline in "weeks" but I'm not sure that is accurate.  

Any general ideas of when 7.0 might land?  

Thank you for your continued work on the project.

**Comment by zugaldia** [comment]
For anyone wondering about the current state of things, please make sure you read https://github.com/nitaliano/react-native-mapbox-gl/issues/1238#issuecomment-461585880 and thread. Thanks!

**Comment by ferdicus** [comment]
@nitaliano: can the community help you with this somehow?

**Comment by nitaliano** [comment]
Closing this out this is happening here https://github.com/react-native-mapbox/react-native-mapbox-gl

**Pull request closed without merging**
