### PR TITLE
Fix ImageSource not support require local file on Android

### PR DESCRIPTION
**Pull request by rogerhokp**
Refer: https://github.com/mapbox/react-native-mapbox-gl/issues/1250

Fix ImageSource`url` not support require local file on Android

### CODE REVIEW

**Comment by matthieucan** [comment]
@rogerhokp thanks!
I can confirm this patch works and fixes #1250
Is there a blocker to get it merged?

**Comment by pinpong** [comment]
Why this PR is not merged yet?

**Comment by nitaliano** [comment]
@rogerhokp thanks for the PR!

**Comment by janweigel** [comment]
We're still having problems to load images with require if we're in release mode or not connected to the local packager in debug mode.
Error message: "Failed to load source xyz"

If using an image with require(...) for MapboxGL.ImageSource it still throws this error if the url is not a remote URL (https://...) or loaded from the local filesystem (file://...). 
It should be possible to load images provided with the app bundle with require. 

Is there any workaround to reliably load images from the app bundle with require?
Thanks!

**Pull request merged**
