### PR TITLE
libRCTMapboxGL.a -> libRCTMGL.a

### LINKED ISSUE #651: Unable to find libRCTMapboxGL.a
I'm unable to complete step 4 of the [iOS install instructions](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md) because `libRCTMapboxGL.a` isn't an option. What am I missing?

image

### PR DESCRIPTION
**Pull request by stdavis**
Closes #651

### CODE REVIEW

**Comment by nitaliano** [comment]
This is only renamed for `v6` current master does not have this. Closing this out.

**Comment by stdavis** [comment]
Since `yarn add @mapbox/react-native-mapbox-gl` installs v6 you might at least want to put a note in there. Otherwise, some unsuspecting person such as myself won't be able to successfully follow the steps as outlined.

**Comment by nitaliano** [comment]
@stdavis  Great point, I'll update the install instructions

**Comment by stdavis** [comment]
Thanks for the amazing work on this project. It's really awesome.

**Pull request closed without merging**
