### PR TITLE
Replaced RCTSparseArray with NSDictionary

### PR DESCRIPTION
**Pull request by i-tengfei**
https://github.com/facebook/react-native/commit/fa0b45c58b248bad33a339484ac83aaf757c831d

### CODE REVIEW

**Comment by bsudekum** [comment]
Thanks, I'll take look at this later today.

**Comment by bsudekum** [comment]
@mrtone Silly question but how do you init/test an `rc` (release candidate) version?

**Comment by rmevans9** [comment]
@bsudekum You could go into your package.json and change your React Native dependency to "react-native": "^0.16.0-rc", then do a npm install.

**Comment by bsudekum** [comment]
Ah ok, I thought it'd be something more complicated. Tested, works great. Thanks @rmevans9

**Pull request merged**
