### PR TITLE
use boolean value. Fixes #277

### LINKED ISSUE #277: Are YES/NO equivalent to bool?
For this code: https://github.com/mapbox/react-native-mapbox-gl/blob/44311c6ec7a02c39cbaea4a5f242252f965813f8/ios/RCTMapboxGL/RCTMapboxGL.m#L350-L358

``` objc
- (BOOL)mapView:(RCTMapboxGL *)mapView annotationCanShowCallout:(id <MGLAnnotation>)annotation {
    NSString *title = [(RCTMGLAnnotation *) annotation title];
    NSString *subtitle = [(RCTMGLAnnotation *) annotation subtitle];
    if ([title length] != 0 || [subtitle length] != 0 ) {
        return YES;
    } else {
        return NO;
    }
}
```

This would be refactored to 

``` objc
- (BOOL)mapView:(RCTMapboxGL *)mapView annotationCanShowCallout:(id <MGLAnnotation>)annotation {
    NSString *title = [(RCTMGLAnnotation *) annotation title];
    NSString *subtitle = [(RCTMGLAnnotation *) annotation subtitle];
    return ([title length] != 0 || [subtitle length] != 0);
}
```

In JavaScript-land - the original code is a symptom of the "not expecting the results of boolean operations to be values" misunderstanding in JS. Does the same rule apply to objcland? @1ec5 @bsudekum ?

### PR DESCRIPTION
**Pull request by tmcw**
@bsudekum what's the best way to run the iOS bindings so I can test this change?

### CODE REVIEW

**Comment by bsudekum** [comment]
@tmcw https://github.com/mapbox/react-native-mapbox-gl/blob/master/CONTRIBUTING.md

**Comment by tmcw** [comment]
Is there no demo or example app?

**Comment by bsudekum** [comment]
Example app can be found here: https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/example.js

**Comment by tmcw** [comment]
Confirmed this fix.

**Pull request merged**
