### PR TITLE
Adds isUserInteraction to region change payload

### PR DESCRIPTION
**Pull request by nitaliano**
Adds support for https://github.com/mapbox/react-native-mapbox-gl/issues/697

* Region payloads now contain a boolean property called `isUserInteraction`
* [Android] Region update events are now throttled by 500 ms

### CODE REVIEW

**Comment by henrikra** [comment]
Nice!!! Does this fix also when screen is unmounted with MapView Android calls still `onRegionDidChange` event?

**Comment by nitaliano** [comment]
@henrikra I don't think, what my plan is moving forward

* Next PR fix location on Android [userAlignment, userTracking]
* Next next PR update all map events to fire the same amount of times as the iOS SDK

and to use the iOS SDK as the source of truth for functionality. Once those two PR's are done I think that will leave this repo in a really good state.

**Comment by henrikra** [comment]
Sounds great! Keep it up :D

**Comment by kaynz** [comment]
Hi @nitaliano,
thanks for this PR. Just tested it - it's working perfectly :+1:

**Comment by nitaliano** [comment]
Great, will work on getting this merged in

**Pull request merged**
