### PR TITLE
Upgrade to Mapbox Android SDK 5.0.2

### PR DESCRIPTION
**Pull request by jackfengji**
TODO: We cannot get metricsEnabled before initialize the mapbox. So we should change it from constant to property maybe.

### CODE REVIEW

**Comment by jackfengji** [comment]
I also removed guava dependency and make a simple difference API in the library. That's because I don't think we should force user to add guava and enable proguard (because of 65536 limit) when they use mapbox-gl-native.

**Comment by benwalks** [comment]
Hi @jackfengji, I used your PR on my application to try to overcome a bug I was experiencing and it's working great except for one small thing.

To use the updated Android SDK in your PR, I had to update the build tools and SDK version to 24 and had to therefore use `PermissionsAndroid` to get access to both the fine and coarse location services, rather than just listing the permissions required in the manifest.

The map and annotations work as they should, but Mapbox no longer seems to use my phone's location services, even though permissions have been successfully granted.  It may be unrelated to your PR, but I just thought I'd check anyway.  Thanks for the great work.

**Comment by nitaliano** [comment]
@jackfengji Would you mind fixing the conflict or I can take this PR over? Would like to work on getting this merged in

**Comment by jackfengji** [comment]
@nitaliano I have resolved the conflicts. But do you know someone who can get PR merged? I have another iOS PR which has also been waited for long time.

**Comment by nitaliano** [comment]
@jackfengji I can merge it in. I'm maintaining this repo now https://github.com/mapbox/react-native-mapbox-gl/issues/590#issuecomment-322901528

**Comment by jackfengji** [comment]
@nitaliano It's great to hear that Mapbox is finally putting more resources to RN as it's getting more and more popular in app development.

Basically in my opinion, this project should be rewritten in many parts especially the iOS one. Please check my issue #556. I spent at least one week to fix the iOS issues in my own branch so it works for my app but some of them are tricky because I didn't have enough time.

I think you should check Airbnb's Mapview implementation for a reference if you are going to rewrite  this one. :)

**Review by nitaliano — CHANGES_REQUESTED** [review]
I got this working locally we just need to update a few things

1. In ReactNativeMapboxGLModule on L157 it is still referencing MapboxAccountManager.
https://github.com/waijule/react-native-mapbox-gl/blob/17f149a3cc0d26a6c8d633c5b3b05d57414ed4a3/android/src/main/java/com/mapbox/reactnativemapboxgl/ReactNativeMapboxGLModule.java#L157 this should be updated to
`Mapbox.getInstance(context, Mapbox.getAccessToken()).setConnected(connected);`

2. In build.gradle https://github.com/waijule/react-native-mapbox-gl/blob/17f149a3cc0d26a6c8d633c5b3b05d57414ed4a3/android/build.gradle we should update to point to v24 here is mine
```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }

    lintOptions {
        abortOnError false
    }
}

repositories {
    mavenCentral()
}

dependencies {
    compile 'com.facebook.react:react-native:+'
    compile 'com.mapbox.mapboxsdk:mapbox-android-telemetry:2.1.0@aar'
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.0.2@aar') {
        transitive = true
    }
}
```

Once we have those changes done we can get this merged in!

**Comment by nitaliano** [comment]
@jackfengji any update on this?

**Comment by jackfengji** [comment]
Sorry. I just fixed it as you requested and rebase your latest code as well.

**Comment by jackfengji** [comment]
@nitaliano Can we have this merged now? I have changed as you requested. :)

**Comment by nitaliano** [comment]
@jackfengji yes I'll get it merged in today.

**Comment by StasDoskalenko** [comment]
Hey, guys, have you tried 5.1.3 version?

**Comment by nitaliano** [comment]
👍

**Pull request merged**
