### PR TITLE
Fixes #164 - Update install.md

### LINKED ISSUE #164: Using cocoapod?
I try to install this component the easy way with Cocoapod. I have never done that before and the readme.md is not very detailed.

I did:

```
$ react-native init AwesomeProject
$ cd AwesomeProject
$ npm install react-native-mapbox-gl --save
```

then I created a `Podspec`file at the root of the RN project with `pod 'RCTMapboxGL', :path => 'node_modules/react-native-mapbox-gl/ios'` 
and run `pod install`

But I have en error `[!] No 'Podfile' found in the project directory` so where do I need to put the Podfile and what do I need to put inside?

### PR DESCRIPTION
**Pull request by brianjd**

### CODE REVIEW

**Comment by brianjd** [comment]
https://github.com/mapbox/react-native-mapbox-gl/issues/164

**Comment by brianjd** [comment]
Why wasn't this one merged?

**Comment by bsudekum** [comment]
@brianjd I merged https://github.com/mapbox/react-native-mapbox-gl/pull/166/files first. Now there are conflicts. Could you rebase your branch? I think the addition of the `../` is necessary.

**Comment by brianjd** [comment]
@bsudekum Ok, will do.  But considering I submitted my pull with the changes nearly a week prior, I shouldn't be the one to rebase.

**Pull request merged**
