### PR TITLE
How do I get the maps to show up on example?

### PR DESCRIPTION
**Pull request by ctaggart**
Video: https://youtu.be/E1_7leuOU3w

I'm running the example with the latest:
- react-native-mapbox-gl
- react
- react-native
- gradle
- android plugin for gradle

The apps seems fine, but the maps don't show up. Any suggestions for troubleshooting?

### CODE REVIEW

**Comment by nitaliano** [comment]
@ctaggart on the emulator

* click on `...`
* Find the `Location` panel
* Update Latitude/Longitude and click Send

Those examples are expecting a user location which you need to set on the Android emulators, if you're going to test anything location based devices are easier on Android

One quick test could be trying to opening the `Show Click` example and seeing if you see the Map

**Comment by ctaggart** [comment]
No maps are showing up on Show Click either.
Video: https://youtu.be/G9ZgeO5kUto

**Comment by nitaliano** [comment]
Then you're most likely running into this https://github.com/mapbox/react-native-mapbox-gl/issues/1041#issuecomment-375381751

**Comment by ctaggart** [comment]
Thanks! It works now. It looks like it defaults to `Desktop native OpenGL`. `SwiftShader` works but since it is software rendered, it was a bit slow. `ANGLE (D3D11)` set to `Renderer maximum (up to OpenGL 3.1)` is working is the most responsive.

SwiftShader
https://github.com/google/swiftshader

ANGLE
https://chromium.googlesource.com/angle/angle/+/master/README.md

image

**Comment by nitaliano** [comment]
👍 cool glad you got it working, you can follow the `gl-native` issue to see whenever we get this fixed

**Pull request closed without merging**
