### PR TITLE
Release 6.1.2

### PR DESCRIPTION
**Pull request by nitaliano**
This is a short term fix to prevent weird glitches with the accuracy layer on top of fill layers, a more long term fix will be looked into once we update to the boba release

cc @kbauhaus

### CODE REVIEW

**Comment by nitaliano** [comment]
I tested this walking around SF with my Pixel 2, and I tested different positions on my emulator. If there are still places where this get's reproduced please add the exact coordinate and I will test it out right away

**Comment by kbauhausness** [comment]
Thanks @nitaliano. 

@jluxenberg-scoot and @garymccormick, please go ahead and test on your side & confirm if this fixes the overlapping polygons. If you're still seeing the issue in certain areas, as @nitaliano noted above it'd be useful to know the coordinates for those locations.

Related to https://github.com/mapbox/react-native-mapbox-gl/issues/1130

**Comment by garymccormick** [comment]
@kbauhaus @nitaliano thanks for filing this. Do you have instructions for how we can test this from a branch?

**Comment by nitaliano** [comment]
@garymccormick you can point to this branch in your package.json, or you could clone this repo and use the example application that comes bundled with it, and update the `ShowMap` example to point to the map style you would like to test with.

**Pull request merged**
