### PR TITLE
General Bugfixes

### PR DESCRIPTION
**Pull request by nitaliano**
Fixes https://github.com/mapbox/react-native-mapbox-gl/issues/671, https://github.com/mapbox/react-native-mapbox-gl/issues/668, https://github.com/mapbox/react-native-mapbox-gl/issues/679
* Adds support for iconImage string tokens.
* Fixes textOffset and iconOffset not using a `CGVector`.
* Adds example iconImage string tokens.
* Adds ability to create overrides for style types
* Adds missing `sourceLayerID` to `FillLayer`
* Adds example using custom vector source.

### CODE REVIEW

**Comment by nitaliano** [comment]
@mapbox/ios would someone be able to review this https://github.com/mapbox/react-native-mapbox-gl/pull/674/files#diff-a70ee91d2efaddbcb649ad8bbc4f4ba0R66 for me and let me know if this is a stupid way of doing it.

**Comment by pingnattawoot** [comment]
i think...
Should iconImage in SymbolLayer style come from sprite file ? 
just like mapbox-gl

**Comment by boundsj** [comment]
> would someone be able to review this

This approach seems like it will work. Have you thought about edge cases like downloads taking a long time or failing or if you want to be able to cancel pending downloads? Also, is `fetchImages` blocking the main thread while it waits to signal?

It'd be more involved but you may want to consider an implementation using `NSOperationQueue` (a famous iOS image downloading implementation that uses that is https://github.com/rs/SDWebImage/blob/master/SDWebImage/SDWebImageDownloader.m). I can imagine scheduling the image downloads on an operation queue with custom operations that decrement your reference count and call the callback somehow when the count reaches 0.

For what you are trying to do here though, what you have may be fine. I'm not sure I fully understand how native code will be exercised (threading wise) in the context of RN!

**Comment by nitaliano** [comment]
@pingnattawoot it should already support images coming from the sprite sheet and it should be able to handle external images as well that we have to register with the map style. So it would support
* Images from the JS layer
* Images from the native projects themselves(drawables, and *.xcassets)
* Images from the sprite sheet.

**Pull request merged**
