### PR TITLE
[v6] Point Annotation Support

### PR DESCRIPTION
**Pull request by nitaliano**
* Adds support for PointAnnotations with custom views.
* Adds support for Callouts with custom views.

### CODE REVIEW

**Comment by henrikra** [comment]
Will this address problems on v5 also? #647 #661 ? So that they are fixed in v6?

**Comment by nitaliano** [comment]
@henrikra I will test those issues to make sure, but I believe they won't be an issue. Are there any other important issues you know of that you think we should test against before merging?

**Comment by henrikra** [comment]
@nitaliano 
1. There is sometimes issue also on Android that custom markers won't show on map until you touch the map :/
2. On Android touch will never get through custom markers. I think by default you can touch through custom marker and if you want them to respond to touch then user adds TouchableOpacity etc

Those came to my mind :)

**Comment by nitaliano** [comment]
@henrikra I attempted to reproduce some of those issues today and I could not. Keeping my fingers crossed that those issues are resolved with this rewrite.

**Pull request merged**
