### PR TITLE
Update headers for RN@0.40.0

### PR DESCRIPTION
**Pull request by sntran**
React Native has made a breaking change to header paths in [0.40.0](https://github.com/facebook/react-native/releases/tag/v0.40.0).

Besides fixing the headers, this adds `RN@0.40` and `React@15.4.0` as
peer dependencies and bump version.

This PR simply adjusts the headers.

### CODE REVIEW

**Comment by bsudekum** [comment]
> Besides fixing the headers, this adds RN@0.40 and React@15.4.0 as peer dependencies and bump version.

Is adding react and react native as a peer dependency necessary?

**Comment by sntran** [comment]
It breaks compatibility with older version of React Native. For this particular PR, React Native 0.40 is required, so I added it as peer dependency.

**Comment by aksonov** [comment]
@sntran I'm still having compilation error about <React/RCTConvert+CoreLocation.h> file not found (within RCTMapboxGLConversions.h> with this PR, any other path/settings i should alter?

**Comment by aksonov** [comment]
@sntran Maybe it is because CocoaPods settings were not changed?

**Comment by sntran** [comment]
I have always manually installed for iOS so I don't know about CocoaPods. I'll see what I can do.

**Comment by aksonov** [comment]
@sntran Thanks - right, i've just checked with manual install - it works well! Unfortunately some libraries like latest iOS XMPP Framework have only CocoaPods install option...

**Comment by aksonov** [comment]
Looks like RN0.40 cannot be installed via CocoaPods at all now - 'yoga' library is missed (PR is in progress as i see).

**Comment by bsudekum** [comment]
Thanks! I think the cocoapod failures could be fixed with https://github.com/mapbox/react-native-mapbox-gl/pull/499

**Comment by ivankennethwang** [comment]
Any updates when can we have a new release?

**Pull request merged**
