### PR TITLE
Rn 59 support

### PR DESCRIPTION
**Pull request by kristfal**
This PR adds support for RN59, and updates the example app to RN59.

### CODE REVIEW

**Comment by alexiri** [comment]
Works for me! Thanks!!

**Comment by kristfal** [comment]
Great, thanks for testing. 

I’ll test it against our main app this week. It’s a rather complex setup, so may require some further tweaks. If it works there as well, I’ll  merge it in.

**Comment by huanvu** [comment]
Works for me as well.

**Comment by kristfal** [comment]
Works for us as well. Merging!

**Pull request merged**
