### PR TITLE
[fix] Fix isUserInteraction for onRegionWillChange

### LINKED ISSUE #980: onRegionWillChange isUserInteraction always false
This is potentially related to https://github.com/mapbox/react-native-mapbox-gl/issues/901 but it appears that the `isUserInteraction` on the `onRegionWillChange` callback is always false (when user drags/pinches/etc).  This was tested and verified with the **6.0.3-rc1** release.

### PR DESCRIPTION
**Pull request by EricPKerr**
This fixes https://github.com/mapbox/react-native-mapbox-gl/issues/980

`regionWillChangeAnimated` was getting called before `shouldChangeFromCamera`, so the `isUserInteraction` was always false.

This looks at the `MGLCameraChangeReason` bitmask with the updated Mapbox.framework library to make sure the reason bitmask includes any non-programmatic one (like a gesture or panning).

### CODE REVIEW

**Comment by EricPKerr** [comment]
This works for iOS, but I'm not sure how to make the tests pass

**Comment by nitaliano** [comment]
don't worry about the tests failing(since nothing is actually failing). Travis was turned on for all Mapbox repos I need to disable it since we are using circle

**Comment by EricPKerr** [comment]
@nitaliano I've been using this PR in production on iOS for about a month now

**Comment by nitaliano** [comment]
thanks 🍻 !

**Pull request merged**
