### PR TITLE
[v6] Runtime and Data Driven Styling Support

### PR DESCRIPTION
**Pull request by nitaliano**
Adds support for some layers and sources

**Layers**
* FillLayer
* FillExtrusionLayer
* CircleLayer
* SymbolLayer
* LineLayer
* RasterLayer
* BackgroundLayer

**Sources**
* VectorSource
* ShapeSource
* RasterSource

**Other Components**
* MapboxGL.StyleSheet
* Light

Here are some screens

Marker Clustering
marketclustering

Fill Extrusion
buildings

Runtime styling in action
ocean

**cc** @boundsj @zugaldia @bsudekum

### CODE REVIEW

**Comment by 1ec5** [comment]
You might find [this JSON file](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/scripts/style-spec-cocoa-conventions-v8.json) and [this reference document](https://www.mapbox.com/ios-sdk/api/3.6.3/for-style-authors.html) handy as you build out the MGLStyleLayer support for iOS, since many property names and types diverged from the style specification in order to match Objective-C and Swift conventions.

**Comment by nitaliano** [comment]
@1ec5 I'm using the map from that file [here](https://github.com/mapbox/react-native-mapbox-gl/blob/d30f92f7c94356d29bcd460391f7e789e779970b/scripts/autogenHelpers/globals.js#L3) and from there I'm autogenerating all of the style code similar to gl-native

Autogeneration [script](https://github.com/mapbox/react-native-mapbox-gl/blob/d30f92f7c94356d29bcd460391f7e789e779970b/scripts/autogenerate.js)

Templates [directory](https://github.com/mapbox/react-native-mapbox-gl/tree/d30f92f7c94356d29bcd460391f7e789e779970b/scripts/templates)

The style code that gets output for iOS is here
[RCTMGLStyle.h](https://github.com/mapbox/react-native-mapbox-gl/blob/d30f92f7c94356d29bcd460391f7e789e779970b/ios/RCTMGL/RCTMGLStyle.h)
[RCTMGLStyle.m](https://github.com/mapbox/react-native-mapbox-gl/blob/d30f92f7c94356d29bcd460391f7e789e779970b/ios/RCTMGL/RCTMGLStyle.m)

**Comment by henrikra** [comment]
Holy fuck 🥇

**Comment by nitaliano** [comment]
I plan on merging this into `v6` at some point today.

**Pull request merged**
