### PR TITLE
Implement new property disableBackgroundUserTracking to prevent mapbo…

### PR DESCRIPTION
**Pull request by christocracy**
Implement new property `disableBackgroundUserTracking` to prevent `MapBoxGL` property `showsUserLocation: true` from operating in the background.  This property sets up a `LifecycleEventListener` on the `pause/resume` events to toggle `mapView#setMyLocationEnabled`.  Mapbox's location-manager should be able to be **subordinated** to dedicated location-management modules, which might acquire a wakeLock, to take better care to conserve battery-life.  Also fixed a typo in the property name `PROP_USER_LOCATON` to `PROP_USER_LOCATION`

This PR add a new private property in `ReactNativeMapboxGLManager.java` `WritableMap properties` to save the state of user-properties.  This is required by the `LifecycleEventListener`, so it can read the current-state of `PROP_USER_LOCATION`.  This will be handy in the future.

### CODE REVIEW

**Comment by christocracy** [comment]
I see there's conflicts now.  I'll have a look.

**Comment by christocracy** [comment]
Conflicts fixed.

**Comment by christocracy** [comment]
Anybody _care_ about this?  Does nobody there understand the issue involved here or is MapBox _philosophically_ opposed to anything which may limit their ability to vacuum location-data (at the expense of battery-performance of the user's device)?

**Comment by christocracy** [comment]
Is there anyone driving this ship?

**Comment by jordangarside** [comment]
I'm for this

**Comment by BrianSkipworth** [comment]
I need this as well

**Comment by christocracy** [comment]
@bsudekum Do you have anything to say about this PR?

**Comment by bsudekum** [comment]
Hey @christocracy, sorry for the delayed response. We've come to the same conclusion you have - that we should disable location services on sleep and re-enable on wake, and are implementing it upstream in mapbox-gl-native. Here's the [iOS implementation PR in mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native/pull/3641) - @boundsj is currently reviewing that work and we'd be interested in hearing if it solves the problem you're seeing. An Android PR will follow that PR, attacking the same problem on Android, but in core.

To explain our telemetry position: we require that the choice to enable or disable telemetry is available to users, not locked by the application. This is so that we have data to improve our maps - anonymized location data adds up into useful information like turn restrictions and makes it easier to find roads missing from the map. But, like you, we really don't want this to be battery-inefficient - it's a balance, and we're actively improving it to avoid battery drain. Disabling background location is one example of that change, and it's our top priority right now, so it will be changing soon.

**Comment by christocracy** [comment]
I challenge you to find anyone more experienced with "background
geolocation" than myself.  I've been doing this for the last 3 years.  I
make a living creating a battery-efficient, cross-platform module for
Cordova, React Native and native apps.

http://shop.transistorsoft.com/pages/react-native-background-geolocation

Mapbox is a view component -- it _must_ subordinate  control of
location-services in the background to the developer.

On Wednesday, February 17, 2016, Bobby Sudekum notifications@github.com
wrote:

> Hey @christocracy https://github.com/christocracy, sorry for the
> delayed response. We've come to the same conclusion you have - that we
> should disable location services on sleep and re-enable on wake, and are
> implementing it upstream in mapbox-gl-native. Here's the iOS
> implementation PR in mapbox-gl-native
> https://github.com/mapbox/mapbox-gl-native/pull/3641 - @boundsj
> https://github.com/boundsj is currently reviewing that work and we'd be
> interested in hearing if it solves the problem you're seeing. An Android PR
> will follow that PR, attacking the same problem on Android, but in core.
> 
> To explain our telemetry position: we require that the choice to enable or
> disable telemetry is available to users, not locked by the application.
> This is so that we have data to improve our maps - anonymized location data
> adds up into useful information like turn restrictions and makes it easier
> to find roads missing from the map. But, like you, we really don't want
> this to be battery-inefficient - it's a balance, and we're actively
> improving it to avoid battery drain. Disabling background location is one
> example of that change, and it's our top priority right now, so it will be
> changing soon.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mapbox/react-native-mapbox-gl/pull/246#issuecomment-185449944
> .

## 

Snet form Gmail Mobile

**Comment by tmcw** [comment]
Yep @christocracy and for that reason we really value your input on these issues. This particular behavior is better implemented in gl-native, so we're trying to solve the issue there.

**Comment by christocracy** [comment]
@tmcw, @bsudekum I was [hounding folks](https://github.com/mapbox/mapbox-gl-native/pull/2120#issuecomment-140869642) at `mapbox-gl-native` back in August.

**Comment by tmcw** [comment]
Yep, @christocracy, and through your input and deeper research, we're refining our technique. Thanks for the input!

**Comment by jordangarside** [comment]
@christocracy In the meantime does this PR work as intended?
I sort of need this now for my project.
Thanks!

**Comment by christocracy** [comment]
@jordangarside it will turn off location services in when app is paused.

**Comment by christocracy** [comment]
Thanks for your attention @bsudekum and @tmcw

**Pull request closed without merging**
