### PR TITLE
Turn locales on for iOS

### PR DESCRIPTION
**Pull request by henrikra**
Addresses #485 

This enables localisation on iOS and works like a dream 👗 . Documentation here: https://www.mapbox.com/help/change-language/#change-label-language-dynamically

I implemented only iOS because on Android localisation is way different. So if you guys want to help me how to do it then fine. But if not lets merge this? :)

### CODE REVIEW

**Comment by nitaliano** [comment]
I can handle the Android side, do you think this should be a boolean property on the map instead of just always enabling it?

**Comment by henrikra** [comment]
That is one option to pass the boolean from JS yeah. Although I see localised case as the default. Like why someone doesn't want the labels to be same language as your system language :D?

**Comment by nitaliano** [comment]
@henrikra I can't think of any reason why we someone wouldn't want this but maybe a reason exists, so when I add the Android side, I'll switch this to be a boolean just in case there is a use case to want this disabled.

I'll try to work on this PR this week since it's been hanging out for awhile

**Comment by henrikra** [comment]
Good to hear

**Comment by nitaliano** [comment]
@henrikra I made the changes want to look them over? I can rebase then merge this in after

**Comment by henrikra** [comment]
Nice! I didn't know there was mapbox localize plugin for android! Looks good 👍

**Comment by nitaliano** [comment]
great I'll get this merged in today

**Comment by nitaliano** [comment]
thanks again @henrikra for getting this started!

**Pull request merged**
