### PR TITLE
Update to latest Mapbox Native SDKs

### PR DESCRIPTION
**Pull request by nitaliano**
* Updates Android SDK to 5.2.0 (async rendering!)
* Updates iOS SDK to 3.7.0

Note all android applications will need to start targeting Android SDK version `26` install instructions have been updated

### CODE REVIEW

**Comment by bcalik** [comment]
I can't get the Android map working after these changes. I only see white background instead of map.

Ps: My android application is already targeting Android SDK version 26.

@nitaliano

**Comment by nitaliano** [comment]
Is there a specific Android version you're running into this? I'm able to get the example application to run

**Comment by bcalik** [comment]
I use "Pixel 2" emulator using Api 26. I can also run example app, it works great. Everything in gradle files are almost same. ReactNative versions are different, I use 0.51.0, but example app uses 0.49.0, but I don't think that's the issue. I tried hard but I really couldn't detect the issue. Also the only error that I can see from logcat is when I close the application, it tries to destroy mapbox then gives an error, because it wasn't able to init the map.

```
12-11 23:45:49.986 10309-10309/com.bulutfilo E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.bulutfilo, PID: 10309
java.lang.RuntimeException: Unable to destroy activity {com.bulutfilo/com.bulutfilo.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.destroy()' on a null object reference
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4438)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4456)
    at android.app.ActivityThread.-wrap5(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1654)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6541)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.destroy()' on a null object reference
    at com.mapbox.mapboxsdk.maps.MapView.onDestroy(MapView.java:410)
    at com.mapbox.rctmgl.components.mapview.RCTMGLMapView$6.onHostDestroy(RCTMGLMapView.java:845)
    at com.facebook.react.bridge.ReactContext.onHostDestroy(ReactContext.java:228)
    at com.facebook.react.ReactInstanceManager.moveToBeforeCreateLifecycleState(ReactInstanceManager.java:705)
    at com.facebook.react.ReactInstanceManager.onHostDestroy(ReactInstanceManager.java:614)
    at com.facebook.react.ReactInstanceManager.onHostDestroy(ReactInstanceManager.java:628)
    at com.facebook.react.ReactActivityDelegate.onDestroy(ReactActivityDelegate.java:142)
    at com.facebook.react.ReactActivity.onDestroy(ReactActivity.java:72)
    at android.app.Activity.performDestroy(Activity.java:7177)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1248)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4425)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4456) 
    at android.app.ActivityThread.-wrap5(Unknown Source:0) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1654) 
    at android.os.Handler.dispatchMessage(Handler.java:105) 
    at android.os.Looper.loop(Looper.java:164) 
    at android.app.ActivityThread.main(ActivityThread.java:6541) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by nitaliano** [comment]
hmm what styles are you putting on your MapView and parent of the MapView?

**Comment by bcalik** [comment]
Same as example app. Just `{flex: 1}`. It is working well on v6.0.1.

Here is a screenshot with a red background.

screen shot 2017-12-12 at 02 56 11

**Pull request merged**
