### PR TITLE
upgrade to RN0.44

### PR DESCRIPTION
**Pull request by aksonov**
upgrade to RN0.44 (#545, #549)

### CODE REVIEW

**Comment by atarsha** [comment]
@zugaldia What's the process for getting PRs reviewed/merged? There are a few here that could use some attention, and it would be helpful to know how to get them reviewed/merged. I see you're the latest commit (almost a month ago.) Is it you we should look to for these?

**Comment by zugaldia** [comment]
@atarsha Happy to review this PR. This looks good to me, just for background info, could you link the React documentation or release notes where this library renaming was announced?

**Comment by atarsha** [comment]
@zugaldia https://github.com/facebook/react-native/releases/tag/v0.44.0 Shows that MapView was deprecated and removed.

**Comment by zugaldia** [comment]
> iOS
> Breaking changes
> Remove MapViewIOS
> 48f30ec - @mkonicek
> <MapView /> was deprecated for a while, in this release it is removed from react-native.

@atarsha Thank you, I see it now. And simply removing the import fixes it? Doesn't that break the iOS bindings?

**Comment by mmckinley8** [comment]
Please merge this

**Comment by atarsha** [comment]
@zugaldia Yes, the changes in this PR fix the RN 0.44 changes.

**Comment by zugaldia** [comment]
Thank you but my question was a bit more specific: how's removing the `MapKit` import not breaking or affecting the iOS bindings?

**Comment by atarsha** [comment]
@zugaldia I don't know the answer to that. I did not write this Pull Request, but a quick Google search will show you that this is the accepted approach to resolve this issue. In fact, Air B&B (AirMaps) also ran into the same thing.

I am currently using the changes in this PR on my development branch and all is working very well.

I am just advocating getting this merged in so that we do not need to modify library code just to get our projects with MapBox to compile.

**Comment by jjzazuet** [comment]
@zugaldia , I think @atarsha might be referring to some of these issues in AriBnB's RN Maps:

- https://github.com/airbnb/react-native-maps/issues/1193
- https://github.com/airbnb/react-native-maps/issues/1287

If there's something else I could do to help, let me know. Thanks!

**Comment by zugaldia** [comment]
Thank you all for your feedback. I ended up building an iOS test app from this branch and everything seems to be working just fine. Merging this now, thanks @aksonov again for your contribution!

**Comment by apolishch** [comment]
Any idea when we can have a version bump? The latest version on npm/yarn is 5.1.0 which is near enough 6 months old now...

**Pull request merged**
