### PR TITLE
implemented get current bounds [ios]

### PR DESCRIPTION
**Pull request by 22rostislav**
implemented get current bounds on ios

### CODE REVIEW

**Comment by bsudekum** [comment]
@22rostislav you'll also need to implement the JS function [here](https://github.com/mapbox/react-native-mapbox-gl/blob/master/index.ios.js#L6).

Can you also update the ios/readme to reflect the api addition?

**Comment by maqen** [comment]
+1 for this!

**Comment by bsudekum** [comment]
Happy to merge this. It's just needs the JS function added and also merge conflicts to be fixed first.

**Comment by rajkissu** [comment]
+1 :)

**Comment by bsudekum** [comment]
[`getBounds`](https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/RCTMapboxGL/RCTMapboxGLManager.m#L111) is now supported.

**Pull request closed without merging**
