### PR TITLE
[WIP] Upgrade android to v4.0.0

### PR DESCRIPTION
**Pull request by bsudekum**
This upgrades android to v4.0.0 and will unlock offline once done. 

Having a few issues with sorting out MapView and MapboxMap which are producing a blank map + this error: 

```
Error while updating property 'acessToken' of a view managed by: RCTMapbox
```

This occurs on any and all props added to the view. I think this stems to the way I'm managing MapView vs MapboxMap.

Also, what is the new version of `setVisibleCoordinateBounds`?

/cc @bleege @zugaldia @tobrun

### CODE REVIEW

**Comment by tobrun** [comment]
@bsudekum

#### General

The interaction model has changed. We introduced a controller like class `MapboxMap` and removed all the interaction logic from the View class MapView.
You will have to call getMapAsync to get a reference to `MapboxMap.

#### AccessToken error

Related to accessToken error, this seems that this is a reactnative error not a Java Android one.
FWWIW the accessToken is still managed by MapView.. you should be able to call that method directly.

#### setVisibleCoordinateBounds

`setVisibleCoorindateBounds` is now called `LatLngBounds` for parity with Google and can be found in  `CameraUpdateFactory`

``` java
   /**
     * Returns a CameraUpdate that transforms the camera such that the specified latitude/longitude
     * bounds are centered on screen at the greatest possible zoom level.
     * You can specify padding, in order to inset the bounding box from the map view's edges.
     * The returned CameraUpdate has a bearing of 0 and a tilt of 0.
     *
     * @param bounds        Bounds to base the Camera position out of
     * @param paddingLeft   Padding left of the bounds
     * @param paddingTop    Padding top of the bounds
     * @param paddingRight  Padding right of the bounds
     * @param paddingBottom Padding bottom of the bounds
     * @return CameraUpdate Final Camera Position
     */
    public static CameraUpdate newLatLngBounds(@NonNull LatLngBounds bounds, int paddingLeft, int paddingTop, int paddingRight, int paddingBottom) {
        return new CameraBoundsUpdate(bounds, paddingLeft, paddingTop, paddingRight, paddingBottom);
    }
```

Reach out if you have any other questions!

**Comment by dapetcu21** [comment]
Any updates on this?

**Comment by scurtoni** [comment]
Any news about blank map issue?
I'm working on that but I can't figure how to solve the problem.

Here is my code of the createViewInstance in the ReactNativeMapboxGLManager:

`@Override
    public MapView createViewInstance(ThemedReactContext context) {

```
    MapboxAccountManager.start(context, "my-token");

    mapView = new MapView(context);

    mapView.onCreate(null);
    StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
    StrictMode.setThreadPolicy(policy);

    mapView.getMapAsync(new OnMapReadyCallback() {
        @Override
        public void onMapReady(@NonNull MapboxMap m) {

            mapboxMap = m;

            uiSettings = mapboxMap.getUiSettings();
            trackingSettings = mapboxMap.getTrackingSettings();

            mapboxMap.setStyleUrl(Style.MAPBOX_STREETS);

        }
    });

    //init map setting bean
    mapSettings = new MapSettings();
    ctx = context;

    return mapView;
}`
```

any ideas?
Thanks

**Comment by dapetcu21** [comment]
I think this is also superseeded by #365 @tmcw

**Comment by tmcw** [comment]
Yep, I think you're right.

**Pull request closed without merging**
