### PR TITLE
Add shape API

### PR DESCRIPTION
**Pull request by bsudekum**
This adds the ability to add linestring and polygon shapes to the map.

The annotation api now looks like: 

``` json
[{
  "coordinates": "Array of coordinates, lat lng",
  "title": "optional string",
  "subtitle": "optional string",
  "id": "optional string, unique identifier.",
  "rightCalloutAccessory": {
    "url": "Optional. Either remote image or specify via 'image!yourImage.png'",
    "height": "required if url specified",
    "width": "required if url specified",
  },
  "fillColor": "optional hex color value",
  "strokeColor": "optional hex color value",
  "strokeWidth": "optional number width of linestring annotation",
  "alpha": "optional number. Controls opacity of polygons and polylines.",
  "type": "Required: point, polyline, polygon"
}]
```

@1ec5 I'm having issue setting properties of the polyline and polygon. Something like:

``` objective-c
- (CGFloat)mapView:(MGLMapView *)mapView lineWidthForPolylineAnnotation:(id<MGLAnnotation>)annotation
{
    double width = [(RCTMGLAnnotation *) annotation width];
    return width;
}
```

It appears the `annotation` class returned here is a plain `MGLPolyline` and `width` is not a valid selector here. 

Final thought, should the annotation object be straight geojson?

### CODE REVIEW

**Comment by 1ec5** [comment]
Great, this is a huge step towards putting the component into real apps.

> It appears the annotation class returned here is a plain `MGLPolyline` and `width` is not a valid selector here.

That’s because `-[RCTMapboxGL updateAnnotations]` creates MGLPolyline objects, not RCTMGLAnnotation objects. Be careful about how you’re extending RCTMGLAnnotation in this PR: this class has turned into a grab bag of data, some of it set, some of it unset, depending on the kind of annotation you want it to be displayed as. That suggests that you should have two separate classes, one for each kind of annotation.

Note that MGLMapViewDelegate’s many callback methods are an intermediate step towards MapKit parity. The way we’ll probably want to do it eventually is to have an MGLPointAnnotation that backs an MGLPinAnnotationView. MGLPointAnnotation would be the _model_ (containing data), while MGLPinAnnotationView would be the _view_ (basically the model’s stylesheet). Similarly, MGLPolyline would back MGLPolylineRenderer. [MVC](https://developer.apple.com/library/mac/documentation/General/Conceptual/DevPedia-CocoaCore/MVC.html) is one of the most important concepts in Objective-C class design.

But back to this PR: for now, since MGLMapView doesn’t distinguish between annotation models and annotation views, it should suffice to implement RCTMGLPointAnnotation and RCTMGLPolyline depending on the value of `type`.

> Final thought, should the annotation object be straight geojson?

If RCTMapboxGL accepts straight-up GeoJSON, it’s up to RCTMapboxGL to transform that into an array of MGLAnnotation objects (be they RCTMGLPointAnnotation or whatever). Once you cross into Objective-C, the term GeoJSON is meaningless.

**Comment by VonD** [comment]
@bsudekum hi do you have an ETA on this ? anything i can do to help ? thanks

**Comment by bsudekum** [comment]
@VonD I'd say the biggest help would be weighing in on the spec style. Should it be valid geojson, keep it as defined above or something else?

Hoping to have this done by the end of the week.

**Comment by brentvatne** [comment]
I think this looks good - one thing that tripped me up while reading the annotation API was that it seems unrelated to the linestring / polygon shapes initially. Then I thought that well, those are ultimately just map annotations, so that makes sense. How do callout works on lines? Do they appear if you tap anywhere? Are they centered or can you control that?

These questions may make no sense as I just woke up, apologies if so :p

**Comment by christocracy** [comment]
Any ETA on this?

**Comment by sslash** [comment]
Is this branch being merged anytime soon? Would love to use this in an app I have.

**Comment by JonnyBGod** [comment]
+1

**Comment by olliebrennan** [comment]
Any ETA? This is pretty much a blocker for us using MapBox.

**Comment by Roconda** [comment]
+1

**Comment by bsudekum** [comment]
I'm gong to take another stab at this again this week. The short of it is, adding lines/polygons to the map is easy, styling it takes a little bit more finesse. I could do a release now without custom styling but this seems like a big :-1:. Will hopefully have something by the end of the week.

**Comment by bsudekum** [comment]
Closing in favor of https://github.com/mapbox/react-native-mapbox-gl/pull/95

**Pull request closed without merging**
