### PR TITLE
[iOS] Refactored, new functionality, fixed issues

### LINKED ISSUE #133: Static annotation images in 0.14
Since static image loading was changed in react-native 0.14 and `require('image!...')` has been dropped, is there any way to load static images as annotation images?

### PR DESCRIPTION
**Pull request by xxsnakerxx**
- fixed https://github.com/mapbox/react-native-mapbox-gl/issues/133
- added onTap event (https://github.com/mapbox/react-native-mapbox-gl/issues/108)
- added ability to show/hide attributionButton https://github.com/mapbox/react-native-mapbox-gl/issues/96
- fixed (maybe!?) https://github.com/mapbox/react-native-mapbox-gl/issues/128
- added majority of events and methods

phew

### CODE REVIEW

**Comment by bsudekum** [comment]
@xxsnakerxx this is really awesome, thanks for the PR. Do you think this could be split up into 5 different PRs so each bullet can be examined on it's own? Merging all of these at the same time seems dangerous to me.

**Comment by xxsnakerxx** [comment]
@bsudekum I know the PR too big, but it contains much related things I think. I can try to split it, but I have no time for this unfortunately :( because I need adapt these changes to android for my app needs

**Comment by bsudekum** [comment]
@xxsnakerxx there really are some good things in here, but I cannot in good faith merge something so large.

I'm happy to check out smaller, more manageable PRs.

**Comment by xxsnakerxx** [comment]
@bsudekum btw, can you give me any suggestion about how to split these changes? How to split refactoring? JS and ObjC :) Maybe you just check the branch, and push it if all good. If you find any issues I will fix them asap...

**Comment by bsudekum** [comment]
@xxsnakerxx I'd say first start with the refactor, with now api additions. Keep the features on par with where it is now. Then queue up each additional feature into a PR of it's own. 

These additions really look great, but like I said, I can't merge them all at once.

**Comment by xxsnakerxx** [comment]
@bsudekum Do you mean create PR with refactoring of existing code base, and then every next PR should contain refactor + new feature? I mean each next PR should be based on refactor PR?

**Comment by bsudekum** [comment]
> Do you mean create PR with refactoring of existing code base, and then every next PR should contain refactor + new feature?

@xxsnakerxx Yep. We'll merge the refactor then you can add a PR's for each new feature

**Pull request closed without merging**
