### PR TITLE
updated mapbox-android-sdk to 4.2.1 to fix android crash

### PR DESCRIPTION
**Pull request by fab1an**
to fix this crash: https://github.com/mapbox/mapbox-gl-native/issues/6838#issuecomment-269646230

### CODE REVIEW

**Comment by K-Leon** [comment]
I'm seeing this crash https://github.com/mapbox/mapbox-gl-native/issues/7587 too while using 4.2.1. Did u manage to work around this?

**Comment by fab1an** [comment]
No.

**Comment by K-Leon** [comment]
@bsudekum I've seen you merged this commit. Without fix of mapbox/mapbox-gl-native#7587  its breaking react native mapbox.

**Comment by Taakn** [comment]
I am seeing the following error when connectivity changes on 5.1.0

```
java.lang.RuntimeException Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 bqHint=4 (has extras) } in com.mapbox.mapboxsdk.maps.MapView$ConnectivityReceiver@ebb4881 
    LoadedApk.java:1003 android.app.LoadedApk$ReceiverDispatcher$Args.run
    Handler.java:739 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    Looper.java:158 android.os.Looper.loop
    ActivityThread.java:7229 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:1230 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:1120 com.android.internal.os.ZygoteInit.main


Caused: java.lang.NullPointerException Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.setReachability(boolean)' on a null object reference 
    MapView.java:2357 com.mapbox.mapboxsdk.maps.MapView.onConnectivityChanged
    MapView.java:115 com.mapbox.mapboxsdk.maps.MapView.access$3100
    MapView.java:2342 com.mapbox.mapboxsdk.maps.MapView$ConnectivityReceiver.onReceive
    LoadedApk.java:993 android.app.LoadedApk$ReceiverDispatcher$Args.run
    Handler.java:739 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    Looper.java:158 android.os.Looper.loop
    ActivityThread.java:7229 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:1230 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:1120 com.android.internal.os.ZygoteInit.main
```

**Pull request merged**
