### PR TITLE
Fix Android UIManager deprecation warning for RN 0.58

### PR DESCRIPTION
**Pull request by marudy**

### CODE REVIEW

**Comment by kristfal** [comment]
@marudy is this backwards compatible? If so, how far back?

**Comment by goodryanboy** [comment]
Is there any workaround here?

**Comment by kristfal** [comment]
This will break RN 0.57 or lower. Can you add a fallback for those versions?

**Comment by kristfal** [comment]
Closing this. Will accept a PR with a fallback for lower versions of RN.

**Comment by alexiri** [comment]
Hi @kristfal, you rejected this PR but you introduced the change anyway as part of 88f9f7f9279031417a3964c5567a2b77577fbf99. Was this intentional?

**Comment by kristfal** [comment]
Hey, that was not intentional. I think it should have been reversed.

**Pull request closed without merging**
